### ISSUE TITLE
app exits when plugin is called after updating to latest cordova 7.1

### ISSUE THREAD

**Issue by hazaveh** [krish-dev/cordova-plugin-k-imagecropper#6]
Plugin was working perfectly till yesterday after I updated my cordova. 

the app throws an exception. I've got following in logcat:

`12-15 12:33:18.807  5699  6193 I ExifInterface_JNI: Raw image not detected
12-15 12:33:19.011  5699  6193 I ExifInterface_JNI: Raw image not detected
12-15 12:33:19.016  5699  5699 I chromium: [INFO:CONSOLE(24)] "CAMERA SUCCESS OUTPUT:", source: file:///android_asset/www/js/2.451c87c30babd2ddfe65.js (24)
12-15 12:33:19.016  5699  5699 I chromium: [INFO:CONSOLE(24)] "file:///storage/emulated/0/Android/data/com.app.app/cache/apple_jax.jpg?1513312399014", source: file:///android_asset/www/js/2.451c87c30babd2ddfe65.js (24)
12-15 12:33:19.016  5699  5699 I chromium: [INFO:CONSOLE(24)] "CAMERA SUCCESS OUTPUT FINISHED.", source: file:///android_asset/www/js/2.451c87c30babd2ddfe65.js (24)
12-15 12:33:19.016  5699  5699 I chromium: [INFO:CONSOLE(24)] "[object Object]", source: file:///android_asset/www/js/2.451c87c30babd2ddfe65.js (24)
12-15 12:33:19.020  1401 24182 I ActivityManager: START u0 {cmp=com.app.app/com.theartofdev.edmodo.cropper.CropImageActivity (has extras)} from uid 10137 pid 5699 on display 0
12-15 12:33:19.028  5699  6123 D AppTracker: App Event: stop
12-15 12:33:19.028  5699  5699 D CordovaActivity: Paused the activity.
12-15 12:33:19.039  5699  5699 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
12-15 12:33:19.053  5699  5699 D AndroidRuntime: Shutting down VM
12-15 12:33:19.054  5699  5699 E AndroidRuntime: FATAL EXCEPTION: main
12-15 12:33:19.054  5699  5699 E AndroidRuntime: Process: com.app.app, PID: 5699
12-15 12:33:19.054  5699  5699 E AndroidRuntime: java.lang.NoSuchMethodError: No static method getFont(Landroid/content/Context;ILandroid/util/TypedValue;ILandroid/widget/TextView;)Landroid/graphics/Typeface; in class Landroid/support/v4/content/res/ResourcesCompat; or its super classes (declaration of 'android.support.v4.content.res.ResourcesCompat' appears in /data/app/com.app.app-2/base.apk)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.support.v7.widget.TintTypedArray.getFont(TintTypedArray.java:119)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.support.v7.widget.AppCompatTextHelper.updateTypefaceAndStyle(AppCompatTextHelper.java:208)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.support.v7.widget.AppCompatTextHelper.loadFromAttributes(AppCompatTextHelper.java:110)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.support.v7.widget.AppCompatTextHelperV17.loadFromAttributes(AppCompatTextHelperV17.java:38)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:81)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:71)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:67)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.support.v7.widget.Toolbar.setTitle(Toolbar.java:753)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.support.v7.widget.ToolbarWidgetWrapper.setTitleInt(ToolbarWidgetWrapper.java:261)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.support.v7.widget.ToolbarWidgetWrapper.setWindowTitle(ToolbarWidgetWrapper.java:243)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.support.v7.widget.ActionBarOverlayLayout.setWindowTitle(ActionBarOverlayLayout.java:621)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV9.onTitleChanged(AppCompatDelegateImplV9.java:631)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:328)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at com.theartofdev.edmodo.cropper.CropImageActivity.onCreate(CropImageActivity.java:49)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6743)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2774)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2907)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6422)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
12-15 12:33:19.054  5699  5699 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
12-15 12:33:19.054  5699  5699 D AppTracker: App Event: crash
12-15 12:33:19.060  5699  5699 I Process : Sending signal. PID: 5699 SIG: 9`

any help would be appreciated ;)

**Comment by krish-dev** [comment]
resolved in version 1.2.0
