### ISSUE TITLE
Unable to start activity

### ISSUE THREAD

**Issue by cjy37** [krish-dev/cordova-plugin-k-imagecropper#7]
Android min sdk = 16
Android target sdk = 25
Error info:
`
03-12 11:26:51.559: E/AndroidRuntime(24214): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.joinin.***/com.theartofdev.edmodo.cropper.CropImageActivity}: android.view.InflateException: Binary XML file line #0: Error inflating class android.support.v7.widget.ActionBarContextView
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2263)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.app.ActivityThread.access$800(ActivityThread.java:147)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1226)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.os.Looper.loop(Looper.java:136)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.app.ActivityThread.main(ActivityThread.java:5137)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at java.lang.reflect.Method.invoke(Method.java:515)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:617)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at dalvik.system.NativeStart.main(Native Method)
03-12 11:26:51.559: E/AndroidRuntime(24214): Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class android.support.v7.widget.ActionBarContextView
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:406)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:323)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at com.theartofdev.edmodo.cropper.CropImageActivity.onCreate(CropImageActivity.java:58)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.app.Activity.performCreate(Activity.java:5231)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2227)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	... 11 more
03-12 11:26:51.559: E/AndroidRuntime(24214): Caused by: java.lang.reflect.InvocationTargetException
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at java.lang.reflect.Constructor.constructNative(Native Method)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	... 25 more
03-12 11:26:51.559: E/AndroidRuntime(24214): Caused by: java.lang.NoClassDefFoundError: android.support.v4.graphics.drawable.DrawableWrapper
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.support.v7.widget.DrawableUtils.canSafelyMutateDrawable(DrawableUtils.java:149)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.support.v7.widget.AppCompatDrawableManager.tintDrawableUsingColorFilter(AppCompatDrawableManager.java:470)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.support.v7.widget.AppCompatDrawableManager.tintDrawable(AppCompatDrawableManager.java:296)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:205)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.support.v7.widget.AppCompatDrawableManager.createDrawableIfNeeded(AppCompatDrawableManager.java:246)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:77)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.support.v7.widget.ActionBarContextView.<init>(ActionBarContextView.java:69)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	at android.support.v7.widget.ActionBarContextView.<init>(ActionBarContextView.java:61)
03-12 11:26:51.559: E/AndroidRuntime(24214): 	... 28 more
`

**Comment by krish-dev** [comment]
resolved in version 1.2.0
